---
name: create_tag

'on':
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  create_tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{secrets.PUSH_TOKEN}}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: Set up Poetry
        uses: snok/install-poetry@v1

      - name: Tag and push
        run: |
          ./create_tag.sh
...
