---
name: upload_to_coverage_report

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  push:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  codecov:
    name: upload_to_codecov_job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Validate codecov.yml file
        run: |
          ./validate_codecov_yml.sh

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest coverage pylint flake8
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Install language dependencies
        working-directory: ${{github.workspace}}/system_setup_scripts
        run: |
          ./install_all.sh

      - name: Generate coverage data
        run: |
          coverage run --branch -m pytest
          coverage xml --omit="tests/*"

      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v2

      - name: Upload coverage report to Codacy
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: coverage.xml
...
